name: CI
on: [push, pull_request, release]
env:
  DC: ldc-1.23.0

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: ${{ DC }}
        include:
        - os: ubuntu-latest
          EXE: tjc
        - os: windows-latest
          EXE: tjc.exe
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Build release
        shell: bash
        run: |
          cd source
          ldc2 -m64 -O3 -release -boundscheck=off -enable-inlining -flto=full --defaultlib=phobos2-ldc-lto,druntime-ldc-lto -d-version=cli -of=${{matrix.EXE}} -i main.d
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.EXE}}
          path: ./source/${{matrix.EXE}}
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: ${{ DC }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Test
        shell: bash
        run: |
          cd source
          ldc2 -m64 -g -i main.d -unittest -of=test.exe
          ./test.exe
