name: CI
on: [push, pull_request, release]
env:
  DC: ldc-1.23.0

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [ldc-1.23.0]
        include:
        - os: ubuntu-latest
          EXE: tjc
          PLATFORM: linux-amd64
        - os: windows-latest
          EXE: tjc.exe
          PLATFORM: windows-amd64
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Build release
        shell: bash
        run: |
          cd source
          ldc2 -m64 -O3 -release -boundscheck=off -enable-inlining -flto=full --defaultlib=phobos2-ldc-lto,druntime-ldc-lto -d-version=cli -of=${{matrix.EXE}} -i main.d
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.PLATFORM}}
          path: ./source/${{matrix.EXE}}
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [ldc-1.23.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Test
        shell: bash
        run: |
          cd source
          ldc2 -m64 -g -i main.d -unittest -of=test.exe
          ./test.exe
  upload:
    name: Upload build
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: .
      - name: Install GH CLI
        shell: bash
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt -qq update
          sudo apt -qq install gh
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create CI-GH './linux-amd64/tjc#linux-amd64' './windows-amd64/tjc.exe#windows-amd64'
        
